table Payslips
	lineageTag: 7b6c59b2-93dc-40e2-9f2d-3560477a9f12

	measure 'PY Total Netto' = CALCULATE([Total Netto], SAMEPERIODLASTYEAR(DT_Calendar[Date]))
		lineageTag: 135b5a15-223c-4411-95d6-04f3883fdfea

	measure 'Month Netto' = ```
			
			    VAR netto =
			        CALCULATE(MAX(Payslips[Betrag]), Payslips[Lohnart]="Gesetzl. Netto (EBeschV)")
			    RETURN
			        IF(netto >= [Running Total Expenses], "Green", "Red")
			
			```
		lineageTag: 1f197d9d-b47f-401f-b6bc-7d5488aac64e

	measure 'Total Netto' = TOTALYTD(SUM(Payslips[Betrag]),DT_Calendar[Date], CONTAINSSTRING(Payslips[Lohnart], "Netto"))
		lineageTag: 3136a154-ddcd-4f58-a4dd-3e312df0ef6f

	measure 'Total Gross Salary' = CALCULATE(SUM(Payslips[Betrag]), Payslips[Lohnart] = "Gesamtbrutto (EBeschV)")
		lineageTag: b9a2dbf2-f888-4b17-817a-1f7d502a5f47

	measure 'Total Deductions' =
			SUMX(FILTER(Payslips, Payslips[Lohnart] IN {
				"Lohnsteuer, lfd.", "Lohnsteuer, EZ",
				"Krankenversicherung, lfd.", "Rentenversicherung, lfd.",
				"Arbeitslosenvers., lfd.", "Pflegeversicherung, lfd."
			}), Payslips[Betrag])
		lineageTag: ae6b4a9d-047a-4448-a878-b0b90455d0a8

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Employer Payroll Contribution %' =
			(SUMX(FILTER(Payslips, Payslips[Lohnart] = "Summe ges. Abzüge"), Payslips[Betrag])
			/ SUMX(FILTER(Payslips, Payslips[Lohnart] = "Gesamtbrutto (EBeschV)"), Payslips[Betrag]))
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: 647dcdf3-46f2-4298-be0c-52fd45e71290

	measure 'Total Employer Benefits' =
			SUMX(FILTER(Payslips, Payslips[Lohnart] IN {
				"AG Zuschuss Firmenabo", "GwV Jobticket"
			}), Payslips[Betrag])
		lineageTag: 746acc6a-9e00-4bf5-9750-775ff4aa0985

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Net Salary to Gross Salary Ratio (%)' = ```
			(SUMX(FILTER(Payslips, Payslips[Lohnart] = "Gesetzl. Netto (EBeschV)"), Payslips[Betrag])
			/ SUMX(FILTER(Payslips, Payslips[Lohnart] = "Gesamtbrutto (EBeschV)"), Payslips[Betrag])) 
			```
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: 76fce30e-24cb-4676-97e6-6531eb9946ec

	measure 'Running Total Expenses' = TOTALYTD(SUM(Payslips[Betrag]), DT_Calendar[Date])
		lineageTag: 778590dc-62a9-42f0-80bf-666e6f9f4a5f

	column Lohnart
		dataType: string
		lineageTag: 0f454ea0-611c-41de-9558-364d56cc46a6
		summarizeBy: none
		sourceColumn: Lohnart

		annotation SummarizationSetBy = Automatic

	column Betrag
		dataType: double
		formatString: #,0.00
		lineageTag: 93358a82-5506-469f-9c62-d0ea60663c0b
		summarizeBy: none
		sourceColumn: Betrag

		annotation SummarizationSetBy = User

	column Date
		dataType: dateTime
		formatString: yyyy-mm
		lineageTag: 75607164-f28b-4022-a2a8-6babe5c2947a
		summarizeBy: none
		sourceColumn: Date

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

		annotation PBI_FormatHint = {"isDateTimeCustom":true}

	partition Payslips = m
		mode: import
		source =
				let
				    Source = Folder.Files("C:\Users\berlin\Desktop\Payslips"),
				    #"Removed Other Columns" = Table.SelectColumns(Source,{"Name", "Content"}),
				    #"Filtered Hidden Files1" = Table.SelectRows(#"Removed Other Columns", each [Attributes]?[Hidden]? <> true),
				    #"Invoke Custom Function1" = Table.AddColumn(#"Filtered Hidden Files1", "Transform File", each #"Transform File"([Content])),
				    #"Removed Other Columns1" = Table.SelectColumns(#"Invoke Custom Function1", {"Transform File"}),
				    #"Expanded Table Column1" = Table.ExpandTableColumn(#"Removed Other Columns1", "Transform File", Table.ColumnNames(#"Transform File"(#"Sample File"))),
				    #"Changed Type" = Table.TransformColumnTypes(#"Expanded Table Column1",{{"Lohnart", type text}, {"Betrag", type number}, {"Date", type date}}),
				    #"Sorted Rows" = Table.Sort(#"Changed Type",{{"Date", Order.Descending}})
				in
				    #"Sorted Rows"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

